import { NextResponse } from 'next/server';
import { auth } from '@/lib/auth';
import { searchSpotifyTrack, createSpotifyPlaylist, normalizeSpotifyTrackUri } from '@/lib/spotify';
import { AggregatedTrack } from '@/types';

export async function GET() {
  return NextResponse.json({ status: 'Spotify Export API is active' });
}

export async function POST(request: Request) {
  try {
    const session = await auth();
    const accessToken = session?.accessToken;

    if (!session || !accessToken) {
      return NextResponse.json({ error: 'Unauthorized. Please sign in to Spotify first.' }, { status: 401 });
    }

    const body = await request.json();
    const { artistName, tourName, tracks, isPublic } = body;

    if (!tracks || !Array.isArray(tracks) || tracks.length === 0) {
      return NextResponse.json({ error: 'Invalid request: tracks are required.' }, { status: 400 });
    }

    const effectiveArtist = (artistName && typeof artistName === 'string' && artistName.trim() !== '' && artistName.toLowerCase() !== 'unknown artist')
      ? artistName.trim()
      : '';

    console.log(`[Export Route] Processing export: artist="${effectiveArtist || 'Unknown'}", tracksCount=${tracks.length}`);

    // Resolve track URIs in bounded batches
    const trackList = tracks as AggregatedTrack[];
    const BATCH_SIZE = 5;
    const resolvedItems: Array<{ uri: string; name: string; artist: string } | null> = [];

    for (let i = 0; i < trackList.length; i += BATCH_SIZE) {
      const batch = trackList.slice(i, i + BATCH_SIZE);
      const batchResults = await Promise.all(
        batch.map(async (track) => {
          const normalizedExisting = track.spotifyUri ? normalizeSpotifyTrackUri(track.spotifyUri) : null;
          if (normalizedExisting) {
            return {
              uri: normalizedExisting,
              name: track.name,
              artist: (track.isCover && track.coverArtist) ? track.coverArtist : effectiveArtist,
            };
          }

          const searchArtist = (track.isCover && track.coverArtist)
            ? track.coverArtist
            : effectiveArtist;

          const result = await searchSpotifyTrack(searchArtist, track.name, accessToken);
          const resolvedUri = result?.uri ? normalizeSpotifyTrackUri(result.uri) : null;
          if (resolvedUri) {
            return {
              uri: resolvedUri,
              name: track.name,
              artist: result?.artists?.[0]?.name || searchArtist,
            };
          }
          return null;
        })
      );
      resolvedItems.push(...batchResults);
    }

    const validMatches = resolvedItems.filter((item): item is { uri: string; name: string; artist: string } => Boolean(item && item.uri));
    const trackUris = validMatches.map((m) => m.uri);

    console.log(`[Export Route] Resolved ${trackUris.length} / ${tracks.length} Spotify track URIs.`);

    if (trackUris.length === 0) {
      return NextResponse.json({ error: 'No matching tracks could be resolved on Spotify.' }, { status: 404 });
    }

    // Determine clean artist title for the playlist
    const fallbackArtist = validMatches[0]?.artist || 'Live Artist';
    const displayArtist = effectiveArtist || fallbackArtist;
    const cleanTour = tourName && tourName !== 'undefined' ? tourName : 'Live Setlist';
    const playlistName = `${displayArtist} - ${cleanTour}`;
    const description = `Live setlist playlist generated by SetDeck with ${trackUris.length} tracks.`;
    const userId = session.providerAccountId;

    const playlist = await createSpotifyPlaylist(
      userId,
      playlistName,
      description,
      trackUris,
      accessToken,
      Boolean(isPublic)
    );

    return NextResponse.json({
      url: playlist.external_urls?.spotify || `https://open.spotify.com/playlist/${playlist.id}`,
      imageUrl: playlist.images?.[0]?.url,
      id: playlist.id,
      name: playlist.name,
      tracksCount: trackUris.length,
    });
  } catch (error: unknown) {
    console.error('[Export Route] Spotify Export Error:', error);
    const message = error instanceof Error ? error.message : 'Failed to create playlist on Spotify';
    const isAuthErr = message.includes('403') || message.includes('401') || message.includes('permission') || message.includes('scope') || message.includes('reconnect');
    return NextResponse.json({ error: message, needReauth: isAuthErr }, { status: isAuthErr ? 403 : 500 });
  }
}
