import { NextResponse } from 'next/server';
import { auth } from '@/lib/auth';
import { searchSpotifyTrack, createSpotifyPlaylist } from '@/lib/spotify';
import { AggregatedTrack } from '@/types';

export async function POST(request: Request) {
  const session = await auth();
  
  const accessToken = session?.accessToken as string | undefined;

  if (!session || !accessToken) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }

  const { artistName, tourName, tracks, isPublic } = await request.json();

  if (!artistName || !tourName || !tracks || !Array.isArray(tracks)) {
    return NextResponse.json({ error: 'Invalid request body' }, { status: 400 });
  }

  try {
    const trackUris: string[] = [];

    // Search for each track on Spotify to get URIs
    for (const track of tracks as AggregatedTrack[]) {
      const searchArtist = track.isCover && track.coverArtist ? track.coverArtist : artistName;
      const result = await searchSpotifyTrack(searchArtist, track.name, accessToken);
      
      if (result) {
        trackUris.push(result.uri);
      }
      // Delay slightly to respect rate limits if needed (optional)
      // await new Promise((r) => setTimeout(r, 50));
    }

    if (trackUris.length === 0) {
      return NextResponse.json({ error: 'No matching tracks found on Spotify' }, { status: 404 });
    }

    const playlistName = `${artistName} - ${tourName}`;
    const description = `Live warm-up playlist generated by SetDeck based on the last recent shows.`;

    // Extract providerAccountId which is Spotify User ID
    const userId = session.providerAccountId as string;

    const playlist = await createSpotifyPlaylist(
      userId,
      playlistName,
      description,
      trackUris,
      accessToken,
      isPublic
    );

    return NextResponse.json({
      url: playlist.external_urls.spotify,
      imageUrl: playlist.images?.[0]?.url,
    });
  } catch (error: unknown) {
    console.error('Spotify Export Error:', error);
    return NextResponse.json({ error: 'Failed to create playlist' }, { status: 500 });
  }
}
