import { NextResponse } from 'next/server';
import { auth } from '@/lib/auth';
import { searchSpotifyTrack, createSpotifyPlaylist } from '@/lib/spotify';
import { AggregatedTrack } from '@/types';

export async function POST(request: Request) {
  try {
    const session = await auth();
    const accessToken = session?.accessToken;

    if (!session || !accessToken) {
      return NextResponse.json({ error: 'Unauthorized. Please sign in to Spotify first.' }, { status: 401 });
    }

    const body = await request.json();
    const { artistName, tourName, tracks, isPublic } = body;

    if (!artistName || !tracks || !Array.isArray(tracks) || tracks.length === 0) {
      return NextResponse.json({ error: 'Invalid request: artist and tracks are required.' }, { status: 400 });
    }

    // Collect track URIs: Use pre-existing spotifyUri or search concurrently
    const resolvedUris = await Promise.all(
      (tracks as AggregatedTrack[]).map(async (track) => {
        if (track.spotifyUri) return track.spotifyUri;

        const searchArtist = track.isCover && track.coverArtist ? track.coverArtist : artistName;
        const result = await searchSpotifyTrack(searchArtist, track.name, accessToken);
        return result?.uri || null;
      })
    );

    const trackUris = resolvedUris.filter((uri): uri is string => Boolean(uri));

    if (trackUris.length === 0) {
      return NextResponse.json({ error: 'No matching tracks could be resolved on Spotify.' }, { status: 404 });
    }

    const playlistName = `${artistName} - ${tourName || 'Live Setlist'}`;
    const description = `Live warm-up playlist generated by SetDeck based on recent tour setlists.`;
    const userId = session.providerAccountId;

    const playlist = await createSpotifyPlaylist(
      userId,
      playlistName,
      description,
      trackUris,
      accessToken,
      Boolean(isPublic)
    );

    return NextResponse.json({
      url: playlist.external_urls?.spotify || `https://open.spotify.com/playlist/${playlist.id}`,
      imageUrl: playlist.images?.[0]?.url,
      id: playlist.id,
      name: playlist.name,
      tracksCount: trackUris.length,
    });
  } catch (error: unknown) {
    console.error('Spotify Export Error:', error);
    const message = error instanceof Error ? error.message : 'Failed to create playlist on Spotify';
    return NextResponse.json({ error: message }, { status: 500 });
  }
}
